check_boot_jars: Add CAF IMS to whitelist
Fixes:
Error: /srv/out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/classes.jar
  contains class file org/codeaurora/ims/ImsMultiIdentityControllerBase.class,
  which is not in the whitelist
Error: /srv/out/target/common/obj/JAVA_LIBRARIES/telephony-ext_intermediates/classes.jar
  contains class file org/codeaurora/internal/Client.class,
  which is not in the whitelist

(The error only pops up when using "make dist")

Signed-off-by: เจียน <jianrzy@naver.com>